MusicClassification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('predictor.urls')),
    path('admin/', admin.site.urls)
]


if settings.DEBUG:
    #test mode
    from django.conf.urls.static import static
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predictor/urls.py
from django.urls import path
from . import views

app_name = 'predictor'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('result/', views.model_form_upload, name='result'),
]

predictor/models.py
from django.db import models


class Document(models.Model):
    file = models.FileField(upload_to='file/')

predictor/forms.py
from django import forms


class DocumentForm(forms.Form):
    def is_valid(*args, **kwargs):
        return True

    file = forms.FileField(help_text='Valid .mp3 file')

predictor/views.py
import warnings

from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import ListView

from .Metadata import get_metadata
from .forms import DocumentForm
from .models import Document
from .predict import predict_gen

warnings.simplefilter('ignore')


class IndexView(ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return True


def model_form_upload(request):
    documents = Document.objects.all()
    if request.method == 'POST':
        if len(request.FILES) == 0:
            messages.error(request, 'Upload a file')
            return redirect("predictor:index")

        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            upload_file = request.FILES['document']
            if not upload_file.name.endswith('.wav'):
                messages.error(request, 'Only .wav file type is allowed')
                return redirect("predictor:index")
            meta = get_metadata(upload_file)

            genre = predict_gen(meta)

            context = {'genre': genre}
            return render(request, 'music/result.html', context)

    else:
        form = DocumentForm()

    return render(request, 'music/result.html', {'documents': documents, 'form': form})

predictor/templates/music/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Music Genre Classification</title>
	<link rel="icon" href="{% static 'music/images/headphone.png' %}">
</head>

<body id="page-top">

	  <!-- Preloader -->
<div class="spinner-wrapper">
      <div class="spinner">
          <div class="bounce1"></div>
          <div class="bounce2"></div>
          <div class="bounce3"></div>
      </div>
 </div>
  <!-- end of preloader -->

  {% include 'music/snippets/nav.html' %}

   <div class="content h-100">

    {% block content %}

    <!-- content for different pages here -->

    {% endblock content %}
  </div>


  {% include 'music/snippets/js.html' %}

</body>
<script>
    $(document).ready(function(){
        $('.up-input').change(function () {
            $('.up-p').text(this.files.length + " file(s) selected");
        });
    });

    
</script>
<!-- Bootstrap core JavaScript -->

</html>

predictor/templates/music/index.html
{% extends 'music/base.html' %}
{% load static %}

<!-- Favicon  -->
<head>
    <link rel="icon" href="{% static 'music/images/headphone.png' %}">
</head>
<body data-spy="scroll" data-target=".fixed-top">

<!-- Preloader -->
<div class="spinner-wrapper">
    <div class="spinner">
        <div class="bounce1"></div>
        <div class="bounce2"></div>
        <div class="bounce3"></div>
    </div>
</div>
<!-- end of preloader -->



{% block content %}
    <!-- Header -->
    <header id="header" class="header h-100 d-flex align-items-center justify-content-center">
        <div class="header-content w-100">
            <div class="container mt-5">
                <div class="row">
                    <div class="col-lg-12" style="margin-bottom: 6rem;">
                        <div class="p-heading p-large">Here you can drag and drop your music file or click on the area
                            and upload your music file to check genre of the music.
                        </div>
                    </div> <!-- end of col -->
                </div>
                <div class="row">
                    <form action="{% url 'predictor:result' %}" method="POST" enctype="multipart/form-data"
                          class="up-form d-flex flex-column align-items-center">
                        {% csrf_token %}
                        <input type="file" name='document' multiple="" class="up-input">
                        {{ form.as_table }}
                        <p class="up-p">Drag your music file here or click in this area.</p>
                        <button type="submit" class="btn btn-sm btn-success mt-5" style="width: 30vh;">Check</button>
                        {% include 'music/messages.html' %}
                    </form>
                </div> <!-- end of row -->
            </div> <!-- end of container -->
        </div> <!-- end of header-content -->
        </div>
    </header> <!-- end of header -->
    <!-- end of header -->
    <!-- File Upload -->

{% endblock %}

</body>

predictor/templates/music/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <div style="text-align: center;"><span style="font-size: x-large; color: red; ">{{ message }}</span></div>
    </div>
{% endfor %}

predictor/templates/music/result.html
{{ file.name }}
{% load static %}
<html lang="en">
<head>

    <title>Music Genre Classification</title>

    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet">
    <link href="{% static 'music/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'music/css/fontawesome-all.css' %}" rel="stylesheet">
    <link href="{% static 'music/css/swiper.css' %}" rel="stylesheet">
    <link href="{% static 'music/css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'music/css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'music/css/mystyle.css' %}" rel="stylesheet">

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'music/images/headphone.png' %}">

</head>

<body data-spy="scroll" data-target=".fixed-top">
<!-- Preloader -->
<div class="spinner-wrapper">
    <div class="spinner">
        <div class="bounce1"></div>
        <div class="bounce2"></div>
        <div class="bounce3"></div>
    </div>
</div>
<!-- end of preloader -->


<div id="features" class="tabs h-100 result">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Your Music's Genre is</h2>
                <div class="col-md-12">
                    <div class="row mt-5">
                        <div class="col-md-4 offset-md-4">
                            <div class="card right-pane">
                                <div class="card-body d-flex align-items-center justify-content-center">
                                    <div class="card-icon d-flex align-items-center justify-content-center"
                                         style="height: 38vh; width: 38vh; background-color: blueviolet">
                                        <h3>
                                            <i>
                                                {{ genre }}
                                            </i>
                                        </h3>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div>
</div>


{% include 'music/snippets/js.html' %}
</body>
</html>

predictor/templates/music/snippets/js.html
{% load static %}
<!-- Scripts -->
<script src="{% static 'music/js/jquery.min.js' %}"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
<script src="{% static 'music/js/jquery.simple-text-rotator.js' %}"></script>
<script src="{% static 'music/js/jquery.simple-text-rotator.min.js' %}"></script>
<script src="{% static 'music/js/popper.min.js' %}"></script> <!-- Popper tooltip library for Bootstrap -->
<script src="{% static 'music/js/bootstrap.min.js' %}"></script> <!-- Bootstrap framework -->
<script src="{% static 'music/js/jquery.easing.min.js' %}"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
<script src="{% static 'music/js/swiper.min.js' %}"></script> <!-- Swiper for image and text sliders -->
<script src="{% static 'music/js/jquery.magnific-popup.js' %}"></script> <!-- Magnific Popup for lightboxes -->
<script src="{% static 'music/js/morphext.min.js' %}"></script> <!-- Morphtext rotating text in the header -->
<script src="{% static 'music/js/validator.min.js' %}"></script> <!-- Validator.js - Bootstrap plugin that validates forms -->
<script src="{% static 'music/js/scripts.js' %}"></script> <!-- Custom scripts -->
<script src="https://kit.fontawesome.com/99cff280a5.js' %}"></script>
<script src="{% static 'music/js/chart.bundle.js' %}"></script>
<script src="{% static 'music/js/utils.js' %}"></script>

predictor/templates/music/snippets/nav.html
{% load static %}
<!-- Styles -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700,700i" rel="stylesheet">
<link href="{% static 'music/css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'music/css/fontawesome-all.css' %}" rel="stylesheet">
<link href="{% static 'music/css/swiper.css' %}" rel="stylesheet">
<link href="{% static 'music/css/magnific-popup.css' %}" rel="stylesheet">
<link href="{% static 'music/css/styles.css' %}" rel="stylesheet">
<link href="{% static 'music/css/mystyle.css' %}" rel="stylesheet">
<link href="{% static 'music/css/simpletextrotator.css' %}" rel="stylesheet">

<!-- Navbar -->
<nav class="navbar navbar-expand-md navbar-dark navbar-custom fixed-top" style="height: 15%">
    <!-- Text Logo - Use this if you don't have a graphic logo -->
    <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">Leno</a> -->

    <a class="navbar-brand" style="text-decoration: none;" href="{% url 'predictor:index' %}"><span
            style="color: #8ac6d1; ">MUSIC GENRE CLASSIFIER</span></a>

    <!-- Mobile Menu Toggle Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- end of mobile menu toggle button -->
</nav> <!-- end of navbar -->
<!-- end of navbar -->